### PR TITLE
Bugfix

### PR DESCRIPTION
**Pull request by jackcarlisle**
## ready for review

* fix for the rendering bug that we discovered

#32

### CODE REVIEW

**Comment by jrans** [comment]
@jackcarlisle  thanks for this!

**Comment by nelsonic** [comment]
@jackcarlisle & @jrans any idea why the _build_ for this fix failed: 
https://travis-ci.org/dwyl/hapi-riot/builds/173886327
hapi-riot-fail

**Comment by jrans** [comment]
@nelsonic sorry, bad process by me, trigger happy merging before CI had done its thing meant branches were no longer found, reran build on master and all ok

**Comment by jackcarlisle** [comment]
screen shot 2016-11-07 at 14 03 04

**Comment by nelsonic** [comment]
@jackcarlisle fair enough. but _be patient_... 😉 
one rule

**Pull request merged**
